package com.dk_power.power_plant_java.dto.files.clone;

import com.dk_power.power_plant_java.dto.permits.loto_point.LotoPointDto;

/**
 * A LOTO point on the SOURCE equipment whose counterpart could not be auto-linked
 * because no DB row matched the tag-swap. The {@code suggested} DTO is the
 * unsaved transformed payload (tag/desc swapped 01↔02) that the user can accept
 * (saves a new LotoPoint and links it to {@code newEquipmentId}) or skip.
 *
 * <p>Generated by the existing {@code NgLotoPointService.findUnitCounterpart}
 * path when {@code isNew=true}.
 */
public record LotoSuggestionDto(
    Long newEquipmentId,
    Long sourceLotoPointId,
    LotoPointDto suggested
) {}
