######################################################################################
# PROD Profile - Production Database
######################################################################################
spring.datasource.url=jdbc:h2:file:./db/proddb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE

######################################################################################
# PROD Profile - File Storage
######################################################################################
files.root.path=${user.dir}${file.separator}uploads-prod
files.relative.path=uploads-prod
