import { Validators } from '@angular/forms';
import { BaseDto, BaseModel } from '../base/base.model';
import { Option } from '../option.model';
import { FormField } from '../ui/form-field.model';
import { Column } from '../column.model';
import { WorkRequestDto } from './work-request.model';
import { ValueDto } from '../value.model';
import { WorkAreaDto } from './work-area.model';
import { WorkCategoryProfileDto } from './work-category-profile.model';
import { mergeSwHazards } from '../../utils/hazard-merge.util';


export class SwHazards {
  // Column 1 — * requires Plant Manager approval, ** requires Energized Electrical WP
  highTemp: boolean = false;
  highPressure: boolean = false;
  hazardousFlammablePipingMaint: boolean = false;
  electricalTesting599V: boolean = false;
  energized: boolean = false;
  storedEnergy: boolean = false;
  eyeHazard: boolean = false;
  egressAccess: boolean = false;
  ergonomicHazard: boolean = false;
  // Column 2
  fallingObject: boolean = false;
  highNoise: boolean = false;
  dustParticulate: boolean = false;
  combustibleDust: boolean = false;
  fireHazard: boolean = false;
  hotSurface: boolean = false;
  slippery: boolean = false;
  ventilationRequired: boolean = false;
  lightingRestrictions: boolean = false;
  exposedRotatingParts: boolean = false;
  // Column 3
  chemicalExposure: boolean = false;
  liftingHazard: boolean = false;
  handTraps: boolean = false;
  heatColdStress: boolean = false;
  elevatedSurface: boolean = false;
  environmental: boolean = false;
  weatherHazards: boolean = false;
  weatherHazardDescription: string = '';
  testingTroubleshooting50V: boolean = false;
  voltageDescription: string = '';
  hexavalentChromium: boolean = false;
  other: boolean = false;
  otherDescription: string = '';

  constructor(data: Partial<SwHazards> = {}) {
    Object.assign(this, data);
  }
}

export class SwPermits {
  lotoRequired: boolean = false;
  lotoDescription: string = '';
  hotWork: boolean = false;
  hotWorkDescription: string = '';
  confinedSpace: boolean = false;
  confinedSpaceDescription: string = '';
  excavationPermit: boolean = false;
  energizedPermit: boolean = false;
  energizedPermitDescription: string = '';
  ventingPurging: boolean = false;
  ventingPurgingDescription: string = '';
  jha: boolean = true;
  gasTesting: boolean = false;
  liftPlan: boolean = false;
  confSpaceRescuePlanReview: boolean = false;
  fallRescuePlan: boolean = false;
  other: boolean = false;
  otherDescription: string = '';

  constructor(data: Partial<SwPermits> = {}) {
    Object.assign(this, data);
  }
}

export class SwPpe {
  hardhat: boolean = true;
  safetyGlasses: boolean = true;
  hearingProtection: boolean = true;
  boots: boolean = true;
  weldingPpe: boolean = false;
  respiratorDustMask: boolean = false;
  respiratorType: string = '';
  gloves: boolean = true;
  glovesType: string = '';
  gasMonitor: boolean = false;
  tyvekSuit: boolean = false;
  acidSuit: boolean = false;
  barricade: boolean = false;
  faceShield: boolean = false;
  arcFlashPpe: boolean = false;
  classCalRating: string = '';
  gfi: boolean = false;
  purgingVentilation: boolean = false;
  fallProtection: boolean = false;
  fallClearance: string = '';
  other: boolean = false;
  otherDescription: string = '';

  constructor(data: Partial<SwPpe> = {}) {
    Object.assign(this, data);
  }
}

export type SafeWorkFieldName = keyof SafeWorkModel;

export interface SafeWorkModel extends BaseModel {
  date: string | null;
  time: string | null;
  companyPerson: string | null;
  location: string | null;
  workScope: string | null;
  specialInstructions: string | null;
  requestedBy: string | null;
  hazards: SwHazards | null;
  permits: SwPermits | null;
  ppe: SwPpe | null;
  /** Printed as the permit number on paper. Populated server-side by the Red Tag automation. */
  redTagNum: string | null;
  /** Generated by PermitNumberGenerator (D99-yy-MM-dd-NNN). */
  permitNumber: string | null;
  workArea: WorkAreaDto | null;
  permitStatus: ValueDto;
}

export class SafeWorkDto extends BaseDto implements SafeWorkModel {
  date: string | null;
  time: string | null;
  companyPerson: string | null;
  location: string | null;
  workScope: string | null;
  specialInstructions: string | null;
  requestedBy: string | null;
  hazards: SwHazards | null;
  permits: SwPermits | null;
  ppe: SwPpe | null;
  redTagNum: string | null;
  permitNumber: string | null;
  workArea: WorkAreaDto | null;
  permitStatus: ValueDto;

  constructor(data: Partial<SafeWorkModel> = {}) {
    super(data);
    this.date = data.date ?? null;
    this.time = data.time ?? null;
    this.companyPerson = data.companyPerson ?? null;
    this.location = data.location ?? null;
    this.workScope = data.workScope ?? null;
    this.specialInstructions = data.specialInstructions ?? null;
    this.requestedBy = data.requestedBy ?? null;
    this.hazards = data.hazards ?? new SwHazards();
    this.permits = data.permits ?? new SwPermits();
    this.ppe = data.ppe ?? new SwPpe();
    this.redTagNum = data.redTagNum ?? null;
    this.permitNumber = data.permitNumber ?? null;
    this.workArea = data.workArea ? new WorkAreaDto(data.workArea) : null;
    this.permitStatus = data.permitStatus ?? new ValueDto();
    // Defaults live here, not on the FormField: the paper renderer resolves values against the DTO
    // and never reads FormField.initialValue, so the two views of a new permit used to disagree.
    this.date = this.date ?? new Date().toISOString().split('T')[0];
    this.time = this.time ?? new Date().toTimeString().slice(0, 5);
  }

  override toJson(): any {
    return {
      ...super.toJson(),
      date: this.date,
      time: this.time,
      companyPerson: this.companyPerson,
      location: this.location,
      workScope: this.workScope,
      specialInstructions: this.specialInstructions,
      requestedBy: this.requestedBy,
      hazards: this.hazards,
      permits: this.permits,
      ppe: this.ppe,
      redTagNum: this.redTagNum,
      permitNumber: this.permitNumber,
      workArea: this.workArea,
      permitStatus: this.permitStatus?.toJson() ?? null,
    };
  }

  static override fromJson(json: any): SafeWorkDto {
    return new SafeWorkDto({
      ...super.fromJson(json),
      date: json.date|| null,
      time: json.time || null,
      companyPerson: json.companyPerson || null,
      location: json.location || null,
      workScope: json.workScope || null,
      specialInstructions: json.specialInstructions || null,
      requestedBy: json.requestedBy || null,
      hazards: json.hazards || new SwHazards(),
      permits: json.permits || new SwPermits(),
      ppe: json.ppe || new SwPpe(),
      redTagNum: json.redTagNum ?? null,
      permitNumber: json.permitNumber ?? null,
      workArea: json.workArea ? new WorkAreaDto(json.workArea) : null,
      permitStatus: ValueDto.fromJson(json.permitStatus),
    });
  }

  static isValidKey(key: string): key is keyof SafeWorkModel {
    return [
      'id', 'date', 'time', 'companyPerson', 'location', 'workScope',
      'specialInstructions', 'requestedBy', 'redTagNum', 'permitNumber', 'workArea',
      'isVerified', 'name', 'objectType',
      ...Object.keys(SafeWorkDto.getHazardFields(null)), 
      ...Object.keys(SafeWorkDto.getPermitFields(null)),
      ...Object.keys(SafeWorkDto.getPpeFields(null))
    ].includes(key);
  }

  static toFormFields(
    dto: SafeWorkDto,
    locationOptions: Option[] = [],
    fields: (SafeWorkFieldName | 'workArea')[] = [
      'location', 'date', 'time', 'companyPerson', 'workScope',
      'specialInstructions', 'requestedBy', 'redTagNum', 'permitNumber',
      ...Object.keys(SafeWorkDto.getHazardFields(null)) as SafeWorkFieldName[],
      ...Object.keys(SafeWorkDto.getPermitFields(null)) as SafeWorkFieldName[],
      ...Object.keys(SafeWorkDto.getPpeFields(null)) as SafeWorkFieldName[]
    ]
  ): FormField[] {
    const ppeFields = SafeWorkDto.getPpeFields(dto.ppe);
    const permitFields = SafeWorkDto.getPermitFields(dto.permits);
    const hazardFields = SafeWorkDto.getHazardFields(dto.hazards);
    const allFields: { [key: string]: FormField } = {
      id: { name: 'id', label: 'ID', type: 'text', initialValue: dto.id },
      workArea: {
        name: 'workArea',
        label: 'Work Area',
        type: 'work-area-select',
        initialValue: (dto as any).workArea?.id ?? null,
        context: { viewMode: 'map', fallbackText: dto.location },
      },
      date: {
        name: 'date',
        label: 'Date',
        type: 'date',
        validators: [Validators.required],
        initialValue: dto.date ?? new Date().toISOString().split('T')[0]
      },
      time: { 
        name: 'time', 
        label: 'Time', 
        type: 'time', 
        validators: [Validators.required], 
        initialValue: dto.time  ?? new Date().toTimeString().slice(0, 5)
      },
      companyPerson: { 
        name: 'companyPerson', 
        label: 'Company Person', 
        type: 'text', 
        validators: [Validators.required], 
        initialValue: dto.companyPerson 
      },
      location: {
        name: 'location',
        label: 'Location',
        type: 'text',
        // type: 'multi-select',
        options: locationOptions,
        validators: [Validators.required],
        initialValue: dto.location
      },
      workScope: { 
        name: 'workScope', 
        label: 'Work Scope', 
        type: 'textarea', 
        validators: [Validators.required], 
        initialValue: dto.workScope 
      },
      specialInstructions: { 
        name: 'specialInstructions', 
        label: 'Special Instructions', 
        type: 'textarea', 
        initialValue: dto.specialInstructions 
      },
      requestedBy: { 
        name: 'requestedBy', 
        label: 'Requested By', 
        type: 'text', 
        validators: [Validators.required], 
        initialValue: dto.requestedBy 
      },
      redTagNum: { name: 'redTagNum', label: 'Permit #', type: 'text', initialValue: dto.redTagNum },
      permitNumber: { name: 'permitNumber', label: 'Permit Number', type: 'text', initialValue: dto.permitNumber },
      permitStatus: { name: 'permitStatus', label: 'Status', type: 'text', initialValue: dto.permitStatus?.name ?? null },
      isVerified: { 
        name: 'isVerified', 
        label: 'Is Verified', 
        type: 'select', 
        options: [
          { value: 'true', label: 'Yes' },
          { value: 'false', label: 'No' }
        ], 
        initialValue: dto.isVerified?.toString() 
      },
      name: { name: 'name', label: 'Name', type: 'text', initialValue: dto.name },
      objectType: { name: 'objectType', label: 'Object Type', type: 'text', initialValue: dto.objectType },
      ...ppeFields,
      ...permitFields,
      ...hazardFields
    };
  
    return fields.map(fieldName => allFields[fieldName]);
  }

  static toTableColumns(fields: SafeWorkFieldName[] = ['date', 'time', 'companyPerson', 'location', 'workScope', 'requestedBy']): Column[] {
    const allColumns: { [key in SafeWorkFieldName]: Column } = {
      id: { id: 'id', header: 'ID', accessorKey: 'id' },
      date: { id: 'date', header: 'Date', accessorKey: 'date' },
      time: { id: 'time', header: 'Time', accessorKey: 'time' },
      companyPerson: { id: 'companyPerson', header: 'Company Person', accessorKey: 'companyPerson' },
      location: { id: 'location', header: 'Location', accessorKey: 'location' },
      workScope: { id: 'workScope', header: 'Work Scope', accessorKey: 'workScope' },
      specialInstructions: { id: 'specialInstructions', header: 'Special Instructions', accessorKey: 'specialInstructions' },
      requestedBy: { id: 'requestedBy', header: 'Requested By', accessorKey: 'requestedBy' },
      redTagNum: { id: 'redTagNum', header: 'Permit #', accessorKey: 'redTagNum' },
      permitNumber: { id: 'permitNumber', header: 'Permit Number', accessorKey: 'permitNumber' },
      workArea: { id: 'workArea', header: 'Work Area', accessorKey: 'workArea' },
      hazards: { 
        id: 'hazards', 
        header: 'Hazards', 
        accessorFn: (item: SafeWorkDto) => item.hazards ? 'Yes' : 'No'
      },
      permits: { 
        id: 'permits', 
        header: 'Permits', 
        accessorFn: (item: SafeWorkDto) => item.permits ? 'Yes' : 'No'
      },
      ppe: { 
        id: 'ppe', 
        header: 'PPE', 
        accessorFn: (item: SafeWorkDto) => item.ppe ? 'Yes' : 'No'
      },
      name: { id: 'name', header: 'Name', accessorKey: 'name' },
      objectType: { id: 'objectType', header: 'Object Type', accessorKey: 'objectType' },
      isVerified: {
        id: 'isVerified',
        header: 'Verified',
        accessorFn: (item: SafeWorkDto) => item.isVerified ? 'Yes' : 'No',
        conditionalStyling: (item: any, column: Column) =>
            item.isVerified ? { 'background-color': '#90EE90' } : { 'background-color': '#FFCCCB' }
      },
      permitStatus: {
        id: 'permitStatus',
        header: 'Status',
        accessorFn: (item: SafeWorkDto) => item.permitStatus?.name || ''
      },
    };

    return fields.map(fieldName => allColumns[fieldName]);
  }

  static generatePermitFromRequest(request: WorkRequestDto, workArea?: WorkAreaDto | null, categoryProfile?: WorkCategoryProfileDto | null): SafeWorkDto{
    const dto = new SafeWorkDto({
      date: request.dateOfWorkToBePerformed?.split('T')[0] ?? null,
      time: request.timeOfWorkToBePerformed,
      companyPerson: request.company + "/" + request.requestedBy,
      location: request.location,
      workScope: request.workScope,
      requestedBy: request.requestedBy
    });
    // Merge hazards: category standard hazards + work area constant hazards (OR-union)
    dto.hazards = mergeSwHazards(categoryProfile?.standardHazards, workArea?.constantHazards);
    return dto;
  }

  static formatLabel(key: string): string {
    const result = key.replace(/([A-Z])/g, ' $1');
    return result.charAt(0).toUpperCase() + result.slice(1);
  }

  static getHazardOptions(hazards: SwHazards | null): Option[] {
    if(!hazards) return [];
    // Get all keys from the hazards object in a type-safe way
    const hazardKeys = Object.keys(hazards) as (keyof SwHazards)[];

    // Map over the keys to create the desired FormOption structure
    return hazardKeys.map(key => {
      return {
        label: this.formatLabel(key), // 'highTemp' -> 'High Temp'
        key:key,
        value: hazards[key]    // The boolean value (true/false)
      };
    });
  }

  static getPpeOptions(ppe: SwPpe | null): Option[] {
    if(!ppe) return [];
    // Get all keys from the hazards object in a type-safe way
    const hazardKeys = Object.keys(ppe) as (keyof SwPpe)[];

    // Map over the keys to create the desired FormOption structure
    return hazardKeys.map(key => {
      return {
        label: this.formatLabel(key), // 'highTemp' -> 'High Temp'
        key:key,
        value: ppe[key]    // The boolean value (true/false)
      };
    });
  }

  static getPermitOptions(permits: SwPermits | null): Option[] {
    if(!permits) return [];
    // Get all keys from the hazards object in a type-safe way
    const hazardKeys = Object.keys(permits) as (keyof SwPermits)[];

    // Map over the keys to create the desired FormOption structure
    return hazardKeys.map(key => {
      return {
        label: this.formatLabel(key), // 'highTemp' -> 'High Temp'
        key:key,
        value: permits[key]    // The boolean value (true/false)
      };
    });
  }

  static getHazardFields(hazardsDto: SwHazards | null): { [key: string]: FormField } {
    const h = hazardsDto || new SwHazards();
    const group = { label: 'Hazards', orientation: 'horizontal' } as const;
    const cb = (key: keyof SwHazards, label: string): FormField =>
      ({ name: `hazards.${key}`, label, type: 'checkbox', initialValue: h[key] as boolean, group });
    const txt = (key: keyof SwHazards, label: string): FormField =>
      ({ name: `hazards.${key}`, label, type: 'text', initialValue: h[key] as string, group });
    return {
      'hazards.highTemp': cb('highTemp', 'High Temperature (>140F) *'),
      'hazards.highPressure': cb('highPressure', 'High Pressure (>100 psi) *'),
      'hazards.hazardousFlammablePipingMaint': cb('hazardousFlammablePipingMaint', 'Hazardous or Flammable Piping Maint. *'),
      'hazards.electricalTesting599V': cb('electricalTesting599V', 'Electrical Testing >599V *'),
      'hazards.energized': cb('energized', 'Energized Electrical Work (>50V) **'),
      'hazards.storedEnergy': cb('storedEnergy', 'Stored Energy (LOTO)'),
      'hazards.eyeHazard': cb('eyeHazard', 'Eye Hazard'),
      'hazards.egressAccess': cb('egressAccess', 'Egress & Access Hazard'),
      'hazards.ergonomicHazard': cb('ergonomicHazard', 'Ergonomic Hazards'),
      'hazards.fallingObject': cb('fallingObject', 'Falling Object Hazard'),
      'hazards.highNoise': cb('highNoise', 'High Noise'),
      'hazards.dustParticulate': cb('dustParticulate', 'Dust/Particulate'),
      'hazards.combustibleDust': cb('combustibleDust', 'Combustible Dust'),
      'hazards.fireHazard': cb('fireHazard', 'Fire/Explosion Hazard'),
      'hazards.hotSurface': cb('hotSurface', 'Hot Surfaces'),
      'hazards.slippery': cb('slippery', 'Slip/Trip/Fall Hazards'),
      'hazards.ventilationRequired': cb('ventilationRequired', "Ventilation Req'd (Mech/Natural)"),
      'hazards.lightingRestrictions': cb('lightingRestrictions', 'Lighting/Visibility Restrictions'),
      'hazards.exposedRotatingParts': cb('exposedRotatingParts', 'Exposed Rotating Parts'),
      'hazards.chemicalExposure': cb('chemicalExposure', 'Possible Chemical Exposure'),
      'hazards.liftingHazard': cb('liftingHazard', 'Lifting Hazard'),
      'hazards.handTraps': cb('handTraps', 'Hand Traps'),
      'hazards.heatColdStress': cb('heatColdStress', 'Heat/Cold Stress'),
      'hazards.elevatedSurface': cb('elevatedSurface', 'Elevated Work Surface'),
      'hazards.environmental': cb('environmental', 'Environmental Concern'),
      'hazards.weatherHazards': cb('weatherHazards', 'Weather Hazards'),
      'hazards.weatherHazardDescription': txt('weatherHazardDescription', 'Weather Hazard Description'),
      'hazards.testingTroubleshooting50V': cb('testingTroubleshooting50V', 'Testing/Troubleshooting >50V'),
      'hazards.voltageDescription': txt('voltageDescription', 'Voltage'),
      'hazards.hexavalentChromium': cb('hexavalentChromium', 'Hexavalent Chromium (Cr VI)'),
      'hazards.other': cb('other', 'Other'),
      'hazards.otherDescription': txt('otherDescription', 'Other Description'),
    };
  }


  static getPermitFields(permitsDto: SwPermits | null): { [key: string]: FormField } {
    const p = permitsDto || new SwPermits();
    const group = { label: 'Permits', orientation: 'horizontal' } as const;
    const cb = (key: keyof SwPermits, label: string): FormField =>
      ({ name: `permits.${key}`, label, type: 'checkbox', initialValue: p[key] as boolean, group });
    const txt = (key: keyof SwPermits, label: string): FormField =>
      ({ name: `permits.${key}`, label, type: 'text', initialValue: p[key] as string, group });
    return {
      'permits.lotoRequired': cb('lotoRequired', 'LOTO Required'),
      'permits.lotoDescription': txt('lotoDescription', 'LOTO Number'),
      'permits.hotWork': cb('hotWork', 'Hot Work Permit'),
      'permits.hotWorkDescription': txt('hotWorkDescription', 'Hot Work Permit Number'),
      'permits.confinedSpace': cb('confinedSpace', 'Confined Space'),
      'permits.confinedSpaceDescription': txt('confinedSpaceDescription', 'Confined Space Number'),
      'permits.excavationPermit': cb('excavationPermit', 'Excavation Permit'),
      'permits.energizedPermit': cb('energizedPermit', 'Energized Electrical WP'),
      'permits.energizedPermitDescription': txt('energizedPermitDescription', 'Energized Electrical WP Number'),
      'permits.ventingPurging': cb('ventingPurging', 'Venting/Purging Procedure'),
      'permits.ventingPurgingDescription': txt('ventingPurgingDescription', 'Venting/Purging Description'),
      'permits.jha': cb('jha', 'JHA'),
      'permits.gasTesting': cb('gasTesting', 'Air Monitoring within Safe Limits'),
      'permits.liftPlan': cb('liftPlan', 'Lift Plan'),
      'permits.confSpaceRescuePlanReview': cb('confSpaceRescuePlanReview', 'Conf. Space Rescue Plan Review'),
      'permits.fallRescuePlan': cb('fallRescuePlan', 'Fall Rescue Plan'),
      'permits.other': cb('other', 'Other'),
      'permits.otherDescription': txt('otherDescription', 'Other Description'),
    };
  }
  
  static getPpeFields(ppeDto: SwPpe | null): { [key: string]: FormField } {
    const ppe = ppeDto || new SwPpe();
    const group = { label: 'PPE', orientation: 'horizontal' } as const;
    const cb = (key: keyof SwPpe, label: string): FormField =>
      ({ name: `ppe.${key}`, label, type: 'checkbox', initialValue: ppe[key] as boolean, group });
    const txt = (key: keyof SwPpe, label: string): FormField =>
      ({ name: `ppe.${key}`, label, type: 'text', initialValue: ppe[key] as string, group });
    return {
      'ppe.hardhat': cb('hardhat', 'Hardhat'),
      'ppe.safetyGlasses': cb('safetyGlasses', 'Safety Glasses'),
      'ppe.hearingProtection': cb('hearingProtection', 'Hearing Protection'),
      'ppe.boots': cb('boots', 'Protective Footwear'),
      'ppe.weldingPpe': cb('weldingPpe', 'Welding PPE'),
      'ppe.respiratorDustMask': cb('respiratorDustMask', 'Respirator/Dust Mask'),
      'ppe.respiratorType': txt('respiratorType', 'Respirator Type'),
      'ppe.gloves': cb('gloves', 'Protective Gloves'),
      'ppe.glovesType': txt('glovesType', 'Gloves Type'),
      'ppe.gasMonitor': cb('gasMonitor', 'Air Monitor'),
      'ppe.tyvekSuit': cb('tyvekSuit', 'Tyvek Suit'),
      'ppe.acidSuit': cb('acidSuit', 'Acid Suit/Rainsuit'),
      'ppe.barricade': cb('barricade', 'Barricade/Rope Off'),
      'ppe.faceShield': cb('faceShield', 'Face Shield/Goggles'),
      'ppe.arcFlashPpe': cb('arcFlashPpe', 'Arc Flash/Shock PPE'),
      'ppe.classCalRating': txt('classCalRating', 'Class/Cal Rating'),
      'ppe.gfi': cb('gfi', 'GFCI'),
      'ppe.purgingVentilation': cb('purgingVentilation', 'Purging/Ventilation'),
      'ppe.fallProtection': cb('fallProtection', 'Fall Protection (Restraint/Lanyard/SRL)'),
      'ppe.fallClearance': txt('fallClearance', 'Fall Clearance'),
      'ppe.other': cb('other', 'Other'),
      'ppe.otherDescription': txt('otherDescription', 'Other Description'),
    };
  }

}