package com.dk_power.power_plant_java.sevice.sync;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Build-time guard for the ONE weakness of {@code FieldChangeTracker.persistFieldChangesOnConnection}:
 * it INSERTs UPDATE FieldChange rows via a hand-written raw-JDBC statement
 * ({@code FieldChangeTracker.FIELD_CHANGE_INSERT_SQL}) rather than JPA, because a JPA {@code saveAll}
 * from {@code @PostUpdate} is dropped during the commit-time flush for a terminal update.
 *
 * <p>Raw SQL couples the code to the physical column set. If a future change adds/removes/renames a
 * {@code FieldChange} column, the raw INSERT would either throw at runtime or silently omit a column —
 * reintroducing exactly the silent change-log loss this whole fix removed. This test makes that a RED
 * build instead: it asserts the {@code field_change} column set (from INFORMATION_SCHEMA, generated by
 * Hibernate DDL from the entity) equals the column set the raw INSERT binds.
 *
 * <p>If this fails: update {@code FIELD_CHANGE_INSERT_SQL} + its bindings in
 * {@code FieldChangeTracker.persistFieldChangesOnConnection}, then update {@link #INSERT_COLUMNS} here.
 */
@SpringBootTest
@ActiveProfiles("test")
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:fc-schema-drift;DB_CLOSE_DELAY=-1;MODE=LEGACY",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.jpa.hibernate.ddl-auto=create-drop",
        "test.cleanup.enabled=false"
})
@DisplayName("FieldChange raw-INSERT schema-drift guard")
class FieldChangeSchemaDriftGuardIT {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    // RedTagAutomationService uses SikuliX, which fails to init headless; mock it so the context loads.
    @MockBean
    private com.dk_power.power_plant_java.sevice.automation.RedTagAutomationService redTagAutomationService;

    /** The 13 columns bound by FieldChangeTracker.FIELD_CHANGE_INSERT_SQL (kept in lockstep with it). */
    private static final Set<String> INSERT_COLUMNS = Set.of(
            "ID", "ENTITY_TYPE", "ENTITY_ID", "FIELD_NAME", "OLD_VALUE", "NEW_VALUE", "TIMESTAMP",
            "ORIGIN_MACHINE_ID", "ORIGIN_MACHINE_NAME", "SYNCED_TO_MACHINES", "CHANGE_TYPE",
            "RELATIONSHIP_TYPE", "RECEIVED_AT");

    @Test
    @DisplayName("field_change columns exactly match the raw-INSERT column set")
    void fieldChangeColumns_matchRawInsertColumnSet() {
        List<String> actual = jdbcTemplate.queryForList(
                "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FIELD_CHANGE'",
                String.class);

        assertThat(new HashSet<>(actual))
                .as("field_change schema drifted from FieldChangeTracker.FIELD_CHANGE_INSERT_SQL — update the "
                        + "raw INSERT + its column bindings (persistFieldChangesOnConnection) or terminal-update "
                        + "FieldChange rows will be dropped or the INSERT will throw")
                .isEqualTo(INSERT_COLUMNS);
    }
}
