CREATE TABLE REVINFO(ID INT);
CREATE TABLE SAFE_WORK_AUD(ID INT);
BEGIN ATOMIC
  FOR r AS
    SELECT TABLE_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'PUBLIC'
      AND (TABLE_NAME = 'REVINFO' OR TABLE_NAME LIKE '%\_AUD' ESCAPE '\')
  DO
    EXECUTE IMMEDIATE 'DROP TABLE IF EXISTS "' || r.TABLE_NAME || '" CASCADE';
  END FOR;
END;
SELECT COUNT(*) AS CNT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='PUBLIC' AND (TABLE_NAME='REVINFO' OR TABLE_NAME LIKE '%\_AUD' ESCAPE '\');
